[phases.setup]
nixPkgs = ["python313", "nodejs_22"]

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build",
  "pip install -r requirements.txt"
]

[start]
cmd = "uvicorn src.server:app --host 0.0.0.0 --port $PORT"
