import { useEffect, useState } from 'react';
import { Loader2, Plus, Trash2, Rss, Search, Save, Check } from 'lucide-react';
import { getFeeds, saveFeeds } from '../../lib/api';
import type { FeedsConfig } from '../../lib/types';

// hackernews/reddit are kept in the config shape for backward-compat (the backend
// still accepts them) but are intentionally NOT exposed in the UI: they suit a
// tech-news radar, not an executive's industry brief. We pass through whatever was
// already saved without offering a toggle.
const EMPTY: FeedsConfig = {
  enabled: false,
  rss: [],
  google_news: [],
  hackernews: { enabled: false, fetch_top_stories: 30, min_score: 50 },
  reddit: { enabled: false, subreddits: [] },
};

export default function FeedsTab() {
  const [cfg, setCfg] = useState<FeedsConfig>(EMPTY);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);

  const load = async () => {
    setLoading(true);
    try {
      const r = await getFeeds();
      setCfg({ ...EMPTY, ...r.feeds });
    } finally {
      setLoading(false);
    }
  };
  useEffect(() => { load(); }, []);

  const patch = (p: Partial<FeedsConfig>) => { setCfg(c => ({ ...c, ...p })); setSaved(false); };

  const save = async () => {
    setSaving(true);
    try { await saveFeeds(cfg); setSaved(true); setTimeout(() => setSaved(false), 2000); }
    finally { setSaving(false); }
  };

  if (loading) {
    return <div className="flex justify-center py-12"><Loader2 className="animate-spin text-executive-muted" /></div>;
  }

  return (
    <div className="space-y-5">
      <div className="flex items-start justify-between gap-3">
        <div>
          <h3 className="text-sm font-semibold text-executive-text">
            Market Intelligence Feeds <span className="font-normal text-executive-muted">· optional</span>
          </h3>
          <p className="text-xs text-executive-muted mt-0.5 max-w-xl">
            Your daily brief is generated by a live web search driven by your{' '}
            <strong>Market Intelligence instruction</strong>. Feeds are an optional add-on: list the
            industry sites and topic searches <strong>you</strong> trust, and they're pulled in
            alongside that search and scored for relevance to your Business Profile + instruction —
            off-topic items are dropped before they reach your brief.
          </p>
        </div>
        <label className="flex items-center gap-2 text-xs text-executive-text flex-shrink-0">
          <input type="checkbox" checked={cfg.enabled} onChange={e => patch({ enabled: e.target.checked })} />
          Feeds enabled
        </label>
      </div>

      {!cfg.enabled && (
        <div className="text-xs text-executive-muted bg-executive-card border border-executive-border rounded-xl p-3">
          Feeds are <strong className="text-executive-text">off</strong> — your brief currently comes from the live
          web search only, so nothing here is affecting it. Turn on <em>Feeds enabled</em> to also pull from the
          sources you add below.
        </div>
      )}

      {/* RSS feeds — the user's own trusted sources */}
      <Section title="Your trusted sites — RSS / Atom" icon={<Rss size={13} />}
        hint="The industry sources you already follow. Paste a site's RSS / feed URL.">
        {cfg.rss.map((f, i) => (
          <Row key={i} onRemove={() => patch({ rss: cfg.rss.filter((_, j) => j !== i) })}>
            <input
              className="bg-transparent text-xs text-executive-text border-b border-executive-border focus:outline-none w-40"
              value={f.name} placeholder="name"
              onChange={e => { const rss = [...cfg.rss]; rss[i] = { ...f, name: e.target.value }; patch({ rss }); }}
            />
            <input
              className="bg-transparent text-xs text-executive-muted border-b border-executive-border focus:outline-none flex-1 min-w-0"
              value={f.url} placeholder="https://…/feed.xml"
              onChange={e => { const rss = [...cfg.rss]; rss[i] = { ...f, url: e.target.value }; patch({ rss }); }}
            />
            <input type="checkbox" checked={f.enabled !== false}
              onChange={e => { const rss = [...cfg.rss]; rss[i] = { ...f, enabled: e.target.checked }; patch({ rss }); }} />
          </Row>
        ))}
        <AddBtn onClick={() => patch({ rss: [...cfg.rss, { name: '', url: '', enabled: true }] })}>Add a site</AddBtn>
      </Section>

      {/* Google News queries — topic searches */}
      <Section title="Topic searches — Google News" icon={<Search size={13} />}
        hint="Turn any topic into a feed. Use your own focus terms — e.g. “brownfield refinery revamp”, “as-built laser scanning tender”.">
        {cfg.google_news.map((f, i) => (
          <Row key={i} onRemove={() => patch({ google_news: cfg.google_news.filter((_, j) => j !== i) })}>
            <input
              className="bg-transparent text-xs text-executive-text border-b border-executive-border focus:outline-none w-40"
              value={f.name} placeholder="label"
              onChange={e => { const g = [...cfg.google_news]; g[i] = { ...f, name: e.target.value }; patch({ google_news: g }); }}
            />
            <input
              className="bg-transparent text-xs text-executive-muted border-b border-executive-border focus:outline-none flex-1 min-w-0"
              value={f.query} placeholder="search query"
              onChange={e => { const g = [...cfg.google_news]; g[i] = { ...f, query: e.target.value }; patch({ google_news: g }); }}
            />
            <input type="checkbox" checked={f.enabled !== false}
              onChange={e => { const g = [...cfg.google_news]; g[i] = { ...f, enabled: e.target.checked }; patch({ google_news: g }); }} />
          </Row>
        ))}
        <AddBtn onClick={() => patch({ google_news: [...cfg.google_news, { name: '', query: '', enabled: true }] })}>Add a topic search</AddBtn>
      </Section>

      <p className="text-[11px] text-executive-muted px-1">
        Everything you add is scored for relevance to your business before reaching your brief — sources that don't
        match your Market Intelligence instruction are dropped automatically, so adding a feed can't pollute your brief.
      </p>

      <div className="flex justify-end">
        <button onClick={save} disabled={saving}
          className="flex items-center gap-1.5 text-xs px-4 py-2 rounded-lg bg-executive-accent/10 hover:bg-executive-accent/20 border border-executive-accent/30 text-executive-accent disabled:opacity-50">
          {saving ? <Loader2 size={13} className="animate-spin" /> : saved ? <Check size={13} /> : <Save size={13} />}
          {saved ? 'Saved' : 'Save feeds'}
        </button>
      </div>
    </div>
  );
}

function Section({ title, icon, hint, children }: { title: string; icon?: React.ReactNode; hint?: string; children: React.ReactNode }) {
  return (
    <div className="bg-executive-card border border-executive-border rounded-xl p-4">
      <div className="flex items-center gap-1.5 mb-2">
        {icon}<h4 className="text-xs font-semibold text-executive-text uppercase tracking-wide">{title}</h4>
      </div>
      {hint && <p className="text-[11px] text-executive-muted mb-2">{hint}</p>}
      <div className="space-y-1.5">{children}</div>
    </div>
  );
}

function Row({ children, onRemove }: { children: React.ReactNode; onRemove: () => void }) {
  return (
    <div className="flex items-center gap-2">
      {children}
      <button onClick={onRemove} className="text-executive-muted hover:text-rose-400 flex-shrink-0"><Trash2 size={12} /></button>
    </div>
  );
}

function AddBtn({ onClick, children }: { onClick: () => void; children: React.ReactNode }) {
  return (
    <button onClick={onClick} className="text-xs text-executive-accent hover:underline flex items-center gap-1 mt-1">
      <Plus size={11} />{children}
    </button>
  );
}
